"""
Add your CosmosDB NoSQL database schema in this file

For example:

type Book @model {
  id: ID
  title: String
}
"""
type Entry @model {
  item: String!
  game: String!
  modelCount: Int!
  completedDate: String!
  createdAt: String!
}
